name: Optimize Images
on: [push]
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Optimize images
      uses: calibreapp/image-actions@main
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        compressOnly: true
        jpegQuality: '80'
        pngQuality: '80'
        webpQuality: '80'
    - name: Create thumbnails
      run: |
        mkdir -p assets/thumbs
        for img in assets/gallery/*; do
          convert "$img" -resize 300x assets/thumbs/$(basename "$img")
        done
